language: python
python:
  - '2.7'
sudo: required
dist: trusty
install:
  - source cfg4dev
  - pip install coveralls
  # - sudo usermod -aG docker $USER
  # - sudo service docker restart
script:
  - pep8
  - flake8
  - nosetests --with-coverage --cover-branches --cover-erase --cover-package clair_cicd
  - coveralls || true
  - python setup.py sdist --formats=gztar
  - if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_TAG" != "" ]; then ./dockerfiles/build-docker-images.sh -v -t "$TRAVIS_TAG" ./dist/clair-cicd-*.*.*.tar.gz $DOCKERHUB_USERNAME $DOCKERHUB_EMAIL $DOCKERHUB_PASSWORD; fi
